--- #YAML:1.0
name:               XML-LibXML
version:            1.72
abstract:           Interface to Gnome libxml2 xml parsing and DOM library
author:
    - Petr Pajas
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    ExtUtils::MakeMaker:  6.56
    XML::NamespaceSupport:  1.07
    XML::SAX:             0.11
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
