--- #YAML:1.0
name:               XML-LibXML
version:            1.79
abstract:           Interface to Gnome libxml2 xml parsing and DOM library
author:
    - Petr Pajas
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    ExtUtils::MakeMaker:  6.56
    strict:               0
    Test::More:           0
    vars:                 0
    warnings:             0
    XML::NamespaceSupport:  1.07
    XML::SAX:             0.11
resources:
    homepage:    https://bitbucket.org/shlomif/perl-xml-libxml
    repository:  https://bitbucket.org/shlomif/perl-xml-libxml
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
keywords:
    - dom
    - html
    - libxml
    - object oriented
    - oop
    - parse
    - parser
    - parsing
    - pullparser
    - sax
    - sgml
    - xml
    - xpath
    - XPath
    - xs
