=head1 NAME

XML::LibXML::DocumentFragment - XML::LibXML's DOM L2 Document Fragment Implementation

This class is a helper class as described in the DOM Level 2 Specification. It
is implamented as a node without name. All adding, inserting or replacing
functions are aware about document fragments now.

As well all unbound nodes (all nodes that does not belong to any document
subtree) are implicit member of document fragments.

=head1 AUTHORS

Matt Sergeant, 
Christian Glahn, 
=head1 VERSION

1.55

=head1 COPYRIGHT

2001-2002, AxKit.com Ltd; 2001-2003 Christian Glahn, All rights reserved.

=cut
